[package]
name = "masher_linux"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
imgui = "0.9"
imgui-opengl-renderer = "0.12"
libc = "0.2.171"
once_cell = "1.19.0"
ctor = "0.6"